# 48. 도메인 지식 규칙 (사출 물리 · KAMP 가이드북 · SPC 관리도) — 학습 없음

**아이디어**: 불량 에피소드가 1~2개면 데이터에서 규칙을 배우면 과적합 → **규칙을 지식으로 먼저 정하고 데이터는 채점에만**.
12·13번 물리 검증은 Run 안 z(미래 샷 포함)라 분석용이었고, 여기는 전부 **인과적 지표 + 라벨 없는 경보 기준**(현장 그대로 사용 가능).

| 지표 | 겨냥 유형 | 출처 |
|---|---|---|
| I1 재료부족 (−충전 + 속도 − 압력) | 미성형 | 가이드북 |
| I2 쿠션부족 · I3 금형 냉각 · I4 점도↑(흐름저항) | 미성형 | 가이드북 |
| I5 계량지연 · I6 체류시간↑ | 가스 | 가이드북 |
| I7 공정 흔들림(std4) | 가스 | ⚠ RG3에서 나온 가설 (RG3엔 사후, CN7엔 독립) |
| I8 호퍼 과열 추세 | 가스 | ⚠ CN7 R1에서 본 신호 (CN7엔 사후) |

- 단일 지표 / 유형 묶음(OR, 전체 경보율 유지) / 지속(3샷 중 2샷) / **SPC Western Electric 4규칙**(final·std4)
- 경보율 1·3·5% (정상 기준에서 결정), 원형 이동 순열 p, **사전 등록 규칙끼리 Holm 보정** (사후 규칙은 따로 표시)

In [1]:
import pandas as pd
pd.set_option('display.width', 250); pd.set_option('display.max_columns', 40); pd.set_option('display.max_rows', 200)
%load_ext autoreload
%autoreload 2
import domain_rules as DR
R = DR.run(products=('cn7', 'rg3'), n_perm=1000)

[cn7] 완료
[rg3] 완료

## CN7 — 미성형 규칙 / 가스 규칙 (경보율 3%)

In [2]:
display(DR.view(R, 'cn7', rate=0.03, target='미성형').round(3))
display(DR.view(R, 'cn7', rate=0.03, target='가스').round(3))

                         방법 대상유형          출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                   I1 재료부족  미성형        가이드북    사전         0.030          0.057       127  3/15  0/11  3/4      0.024   0.200  0.042    0.031      0.217
1                   I2 쿠션부족  미성형        가이드북    사전         0.007          0.116       204  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
2                  I3 금형 냉각  미성형        가이드북    사전         0.030          0.001        20  1/15  1/11  0/4      0.050   0.067  0.057      NaN        NaN
3              I4 점도↑(흐름저항)  미성형        가이드북    사전         0.030          0.036        62  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
4             미성형 규칙(I1~I4)  미성형     가이드북 묶음    사전         0.025          0.144       264  4/15  1/11  3/4      0.015   0.267  0.029    0.007      0.056
5   미성형 규칙(I1~I4) · 3샷 중 2샷  미성형     가이드북 묶음    사전         0.015          0.098       169  2/15  0/11  2/4      0.012   0.133  0.022    0.041      0.246
6                 전체(I1~I7)   전체     가이드북 묶음    사전         0.029          0.154       287  4/15  1/11  3/4      0.014   0.267  0.026    0.103      0.514
7       전체(I1~I7) · 3샷 중 2샷   전체     가이드북 묶음    사전         0.017          0.110       195  2/15  0/11  2/4      0.010   0.133  0.019    0.307      1.000
8           SPC WE1 · final   전체  SPC 관리도 규칙    사전         0.001          0.004         9  3/15  0/11  3/4      0.333   0.200  0.250    0.035        NaN
9           SPC WE2 · final   전체  SPC 관리도 규칙    사전         0.010          0.015        31  2/15  0/11  2/4      0.065   0.133  0.087    0.128        NaN
10          SPC WE3 · final   전체  SPC 관리도 규칙    사전         0.029          0.030        50  1/15  0/11  1/4      0.020   0.067  0.031    0.292        NaN
11          SPC WE4 · final   전체  SPC 관리도 규칙    사전         0.084          0.020        29  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
12      SPC WE 아무거나 · final   전체  SPC 관리도 규칙    사전         0.098          0.045        80  3/15  0/11  3/4      0.038   0.200  0.063    0.146        NaN
13           SPC WE1 · std4   전체  SPC 관리도 규칙    사전         0.001          0.005         7  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
14           SPC WE2 · std4   전체  SPC 관리도 규칙    사전         0.019          0.020        64  2/15  2/11  0/4      0.031   0.133  0.051    0.362        NaN
15           SPC WE3 · std4   전체  SPC 관리도 규칙    사전         0.079          0.076       211  4/15  4/11  0/4      0.019   0.267  0.035    0.383        NaN
16           SPC WE4 · std4   전체  SPC 관리도 규칙    사전         0.167          0.144       388  5/15  5/11  0/4      0.013   0.333  0.025    0.546        NaN
17       SPC WE 아무거나 · std4   전체  SPC 관리도 규칙    사전         0.193          0.173       442  6/15  6/11  0/4      0.014   0.400  0.026    0.542        NaN

                                    방법 대상유형             출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                              I5 계량지연   가스           가이드북    사전         0.030          0.041        70  2/15  1/11  1/4      0.029   0.133  0.047    0.284      1.000
1                             I6 체류시간↑   가스           가이드북    사전         0.029          0.020       147  3/15  2/11  1/4      0.020   0.200  0.037    0.552      1.000
2                      I7 공정 흔들림(std4)   가스  RG3 가스에서 온 가설    사전         0.030          0.036       102  1/15  1/11  0/4      0.010   0.067  0.017    0.619      1.000
3                          I8 호퍼 과열 추세   가스  CN7 R1에서 본 신호    사후         0.030          0.042        76  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
4                      가스 규칙(I5·I6·I7)   가스        가이드북 묶음    사전         0.030          0.033        80  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
5            가스 규칙(I5·I6·I7) · 3샷 중 2샷   가스        가이드북 묶음    사전         0.011          0.020        54  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
6             가스 규칙 + 호퍼(I5~I8, 사후 포함)   가스       사후 포함 묶음    사후         0.027          0.039        91  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
7   가스 규칙 + 호퍼(I5~I8, 사후 포함) · 3샷 중 2샷   가스       사후 포함 묶음    사후         0.013          0.029        72  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
8                            전체(I1~I7)   전체        가이드북 묶음    사전         0.029          0.154       287  4/15  1/11  3/4      0.014   0.267  0.026    0.103      0.514
9                  전체(I1~I7) · 3샷 중 2샷   전체        가이드북 묶음    사전         0.017          0.110       195  2/15  0/11  2/4      0.010   0.133  0.019    0.307      1.000
10                     SPC WE1 · final   전체     SPC 관리도 규칙    사전         0.001          0.004         9  3/15  0/11  3/4      0.333   0.200  0.250    0.035        NaN
11                     SPC WE2 · final   전체     SPC 관리도 규칙    사전         0.010          0.015        31  2/15  0/11  2/4      0.065   0.133  0.087    0.128        NaN
12                     SPC WE3 · final   전체     SPC 관리도 규칙    사전         0.029          0.030        50  1/15  0/11  1/4      0.020   0.067  0.031    0.292        NaN
13                     SPC WE4 · final   전체     SPC 관리도 규칙    사전         0.084          0.020        29  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
14                 SPC WE 아무거나 · final   전체     SPC 관리도 규칙    사전         0.098          0.045        80  3/15  0/11  3/4      0.038   0.200  0.063    0.146        NaN
15                      SPC WE1 · std4   전체     SPC 관리도 규칙    사전         0.001          0.005         7  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
16                      SPC WE2 · std4   전체     SPC 관리도 규칙    사전         0.019          0.020        64  2/15  2/11  0/4      0.031   0.133  0.051    0.362        NaN
17                      SPC WE3 · std4   전체     SPC 관리도 규칙    사전         0.079          0.076       211  4/15  4/11  0/4      0.019   0.267  0.035    0.383        NaN
18                      SPC WE4 · std4   전체     SPC 관리도 규칙    사전         0.167          0.144       388  5/15  5/11  0/4      0.013   0.333  0.025    0.546        NaN
19                  SPC WE 아무거나 · std4   전체     SPC 관리도 규칙    사전         0.193          0.173       442  6/15  6/11  0/4      0.014   0.400  0.026    0.542        NaN

In [3]:
for rate in (0.01, 0.05):
    print(f'===== CN7 경보율 {rate:.0%}')
    display(DR.view(R, 'cn7', rate=rate).round(3))

===== CN7 경보율 1%

                                    방법 대상유형             출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                              I1 재료부족  미성형           가이드북    사전         0.010          0.020        50  3/15  0/11  3/4      0.060   0.200  0.092    0.012      0.048
1                              I2 쿠션부족  미성형           가이드북    사전         0.007          0.116       204  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
2                             I3 금형 냉각  미성형           가이드북    사전         0.006          0.000         2  1/15  1/11  0/4      0.500   0.067  0.118      NaN        NaN
3                         I4 점도↑(흐름저항)  미성형           가이드북    사전         0.010          0.013        22  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
4                              I5 계량지연   가스           가이드북    사전         0.010          0.016        25  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
5                             I6 체류시간↑   가스           가이드북    사전         0.010          0.004        12  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
6                      I7 공정 흔들림(std4)   가스  RG3 가스에서 온 가설    사전         0.010          0.014        46  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
7                          I8 호퍼 과열 추세   가스  CN7 R1에서 본 신호    사후         0.010          0.017        33  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
8                        미성형 규칙(I1~I4)  미성형        가이드북 묶음    사전         0.009          0.122       216  4/15  1/11  3/4      0.019   0.267  0.035    0.005      0.025
9              미성형 규칙(I1~I4) · 3샷 중 2샷  미성형        가이드북 묶음    사전         0.007          0.084       143  2/15  0/11  2/4      0.014   0.133  0.025    0.017      0.051
10                     가스 규칙(I5·I6·I7)   가스        가이드북 묶음    사전         0.009          0.017        41  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
11           가스 규칙(I5·I6·I7) · 3샷 중 2샷   가스        가이드북 묶음    사전         0.003          0.013        31  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
12            가스 규칙 + 호퍼(I5~I8, 사후 포함)   가스       사후 포함 묶음    사후         0.010          0.022        50  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
13  가스 규칙 + 호퍼(I5~I8, 사후 포함) · 3샷 중 2샷   가스       사후 포함 묶음    사후         0.005          0.018        43  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
14                           전체(I1~I7)   전체        가이드북 묶음    사전         0.009          0.128       223  4/15  1/11  3/4      0.018   0.267  0.034    0.027      0.054
15                 전체(I1~I7) · 3샷 중 2샷   전체        가이드북 묶음    사전         0.007          0.089       150  2/15  0/11  2/4      0.013   0.133  0.024    0.049      0.054
16                     SPC WE1 · final   전체     SPC 관리도 규칙    사전         0.001          0.004         9  3/15  0/11  3/4      0.333   0.200  0.250    0.035        NaN
17                     SPC WE2 · final   전체     SPC 관리도 규칙    사전         0.010          0.015        31  2/15  0/11  2/4      0.065   0.133  0.087    0.128        NaN
18                     SPC WE3 · final   전체     SPC 관리도 규칙    사전         0.029          0.030        50  1/15  0/11  1/4      0.020   0.067  0.031    0.292        NaN
19                     SPC WE4 · final   전체     SPC 관리도 규칙    사전         0.084          0.020        29  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
20                 SPC WE 아무거나 · final   전체     SPC 관리도 규칙    사전         0.098          0.045        80  3/15  0/11  3/4      0.038   0.200  0.063    0.146        NaN
21                      SPC WE1 · std4   전체     SPC 관리도 규칙    사전         0.001          0.005         7  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
22                      SPC WE2 · std4   전체     SPC 관리도 규칙    사전         0.019          0.020        64  2/15  2/11  0/4      0.031   0.133  0.051    0.362        NaN
23                      SPC WE3 · std4   전체     SPC 관리도 규칙    사전         0.079          0.076       211  4/15  4/11  0/4      0.019   0.267  0.035    0.383        NaN
24                      SPC WE4 · std4   전체     SPC 관리도 규칙    사전         0.167          0.144       388  5/15  5/11  0/4      0.013   0.333  0.025    0.546        NaN
25                  SPC WE 아무거나 · std4   전체     SPC 관리도 규칙    사전         0.193          0.173       442  6/15  6/11  0/4      0.014   0.400  0.026    0.542        NaN

===== CN7 경보율 5%

                                    방법 대상유형             출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                              I1 재료부족  미성형           가이드북    사전         0.050          0.082       173  3/15  0/11  3/4      0.017   0.200  0.032    0.032      0.256
1                              I2 쿠션부족  미성형           가이드북    사전         0.007          0.116       204  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
2                             I3 금형 냉각  미성형           가이드북    사전         0.045          0.016        76  4/15  3/11  1/4      0.053   0.267  0.088    0.235      1.000
3                         I4 점도↑(흐름저항)  미성형           가이드북    사전         0.050          0.048        91  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
4                              I5 계량지연   가스           가이드북    사전         0.050          0.073       127  3/15  2/11  1/4      0.024   0.200  0.042    0.168      1.000
5                             I6 체류시간↑   가스           가이드북    사전         0.029          0.020       147  3/15  2/11  1/4      0.020   0.200  0.037    0.552      1.000
6                      I7 공정 흔들림(std4)   가스  RG3 가스에서 온 가설    사전         0.050          0.060       159  3/15  3/11  0/4      0.019   0.200  0.034    0.356      1.000
7                          I8 호퍼 과열 추세   가스  CN7 R1에서 본 신호    사후         0.050          0.072       127  1/15  0/11  1/4      0.008   0.067  0.014      NaN        NaN
8                        미성형 규칙(I1~I4)  미성형        가이드북 묶음    사전         0.031          0.145       266  4/15  1/11  3/4      0.015   0.267  0.028    0.014      0.126
9              미성형 규칙(I1~I4) · 3샷 중 2샷  미성형        가이드북 묶음    사전         0.019          0.098       170  2/15  0/11  2/4      0.012   0.133  0.022    0.049      0.343
10                     가스 규칙(I5·I6·I7)   가스        가이드북 묶음    사전         0.041          0.051       148  1/15  0/11  1/4      0.007   0.067  0.012      NaN        NaN
11           가스 규칙(I5·I6·I7) · 3샷 중 2샷   가스        가이드북 묶음    사전         0.017          0.029        83  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
12            가스 규칙 + 호퍼(I5~I8, 사후 포함)   가스       사후 포함 묶음    사후         0.050          0.061       169  1/15  0/11  1/4      0.006   0.067  0.011      NaN        NaN
13  가스 규칙 + 호퍼(I5~I8, 사후 포함) · 3샷 중 2샷   가스       사후 포함 묶음    사후         0.028          0.042       111  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
14                           전체(I1~I7)   전체        가이드북 묶음    사전         0.049          0.166       318  4/15  1/11  3/4      0.013   0.267  0.024    0.230      1.000
15                 전체(I1~I7) · 3샷 중 2샷   전체        가이드북 묶음    사전         0.026          0.119       219  2/15  0/11  2/4      0.009   0.133  0.017    0.454      1.000
16                     SPC WE1 · final   전체     SPC 관리도 규칙    사전         0.001          0.004         9  3/15  0/11  3/4      0.333   0.200  0.250    0.035        NaN
17                     SPC WE2 · final   전체     SPC 관리도 규칙    사전         0.010          0.015        31  2/15  0/11  2/4      0.065   0.133  0.087    0.128        NaN
18                     SPC WE3 · final   전체     SPC 관리도 규칙    사전         0.029          0.030        50  1/15  0/11  1/4      0.020   0.067  0.031    0.292        NaN
19                     SPC WE4 · final   전체     SPC 관리도 규칙    사전         0.084          0.020        29  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
20                 SPC WE 아무거나 · final   전체     SPC 관리도 규칙    사전         0.098          0.045        80  3/15  0/11  3/4      0.038   0.200  0.063    0.146        NaN
21                      SPC WE1 · std4   전체     SPC 관리도 규칙    사전         0.001          0.005         7  0/15  0/11  0/4      0.000   0.000  0.000      NaN        NaN
22                      SPC WE2 · std4   전체     SPC 관리도 규칙    사전         0.019          0.020        64  2/15  2/11  0/4      0.031   0.133  0.051    0.362        NaN
23                      SPC WE3 · std4   전체     SPC 관리도 규칙    사전         0.079          0.076       211  4/15  4/11  0/4      0.019   0.267  0.035    0.383        NaN
24                      SPC WE4 · std4   전체     SPC 관리도 규칙    사전         0.167          0.144       388  5/15  5/11  0/4      0.013   0.333  0.025    0.546        NaN
25                  SPC WE 아무거나 · std4   전체     SPC 관리도 규칙    사전         0.193          0.173       442  6/15  6/11  0/4      0.014   0.400  0.026    0.542        NaN

## RG3

In [4]:
display(DR.view(R, 'rg3', rate=0.03, target='미성형').round(3))
display(DR.view(R, 'rg3', rate=0.03, target='가스').round(3))
display(DR.view(R, 'rg3', rate=0.05).round(3))

                         방법 대상유형          출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                   I1 재료부족  미성형        가이드북    사전         0.030          0.049        20  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
1                   I2 쿠션부족  미성형        가이드북    사전         0.025          0.049        19  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
2                  I3 금형 냉각  미성형        가이드북    사전         0.027          0.000         0  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
3              I4 점도↑(흐름저항)  미성형        가이드북    사전         0.030          0.000         0  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
4             미성형 규칙(I1~I4)  미성형     가이드북 묶음    사전         0.029          0.024         7  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
5   미성형 규칙(I1~I4) · 3샷 중 2샷  미성형     가이드북 묶음    사전         0.016          0.000         2  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
6                 전체(I1~I7)   전체     가이드북 묶음    사후         0.030          0.000        14  1/25  1/17  0/8      0.071    0.04  0.051    0.481        NaN
7       전체(I1~I7) · 3샷 중 2샷   전체     가이드북 묶음    사후         0.014          0.000         6  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
8           SPC WE1 · final   전체  SPC 관리도 규칙    사전         0.001          0.000         3  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
9           SPC WE2 · final   전체  SPC 관리도 규칙    사전         0.007          0.049         9  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
10          SPC WE3 · final   전체  SPC 관리도 규칙    사전         0.027          0.049        16  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
11          SPC WE4 · final   전체  SPC 관리도 규칙    사전         0.055          0.073        23  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
12      SPC WE 아무거나 · final   전체  SPC 관리도 규칙    사전         0.076          0.171        43  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
13           SPC WE1 · std4   전체  SPC 관리도 규칙    사후         0.001          0.000         4  1/25  1/17  0/8      0.250    0.04  0.069    0.193        NaN
14           SPC WE2 · std4   전체  SPC 관리도 규칙    사후         0.022          0.000        22  1/25  0/17  1/8      0.045    0.04  0.043    0.648        NaN
15           SPC WE3 · std4   전체  SPC 관리도 규칙    사후         0.106          0.220        59  3/25  0/17  3/8      0.051    0.12  0.071    0.403        NaN
16           SPC WE4 · std4   전체  SPC 관리도 규칙    사후         0.235          0.293        93  1/25  0/17  1/8      0.011    0.04  0.017    0.980        NaN
17       SPC WE 아무거나 · std4   전체  SPC 관리도 규칙    사후         0.248          0.390       125  4/25  1/17  3/8      0.032    0.16  0.053    0.701        NaN

                                    방법 대상유형             출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                              I5 계량지연   가스           가이드북    사전         0.030          0.024        23  1/25  1/17  0/8      0.043    0.04  0.042    0.525      1.000
1                             I6 체류시간↑   가스           가이드북    사전         0.024          0.000         6  1/25  1/17  0/8      0.167    0.04  0.065    0.147      0.441
2                      I7 공정 흔들림(std4)   가스  RG3 가스에서 온 가설    사후         0.030          0.024        33  2/25  1/17  1/8      0.061    0.08  0.069    0.678        NaN
3                          I8 호퍼 과열 추세   가스  CN7 R1에서 본 신호    사전         0.030          0.268        57  4/25  2/17  2/8      0.070    0.16  0.098    0.504      1.000
4                      가스 규칙(I5·I6·I7)   가스        가이드북 묶음    사후         0.030          0.000        25  3/25  2/17  1/8      0.120    0.12  0.120    0.182        NaN
5            가스 규칙(I5·I6·I7) · 3샷 중 2샷   가스        가이드북 묶음    사후         0.013          0.000        18  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
6             가스 규칙 + 호퍼(I5~I8, 사후 포함)   가스       사후 포함 묶음    사후         0.029          0.244        50  4/25  3/17  1/8      0.080    0.16  0.107    0.157        NaN
7   가스 규칙 + 호퍼(I5~I8, 사후 포함) · 3샷 중 2샷   가스       사후 포함 묶음    사후         0.013          0.244        40  1/25  0/17  1/8      0.025    0.04  0.031      NaN        NaN
8                            전체(I1~I7)   전체        가이드북 묶음    사후         0.030          0.000        14  1/25  1/17  0/8      0.071    0.04  0.051    0.481        NaN
9                  전체(I1~I7) · 3샷 중 2샷   전체        가이드북 묶음    사후         0.014          0.000         6  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
10                     SPC WE1 · final   전체     SPC 관리도 규칙    사전         0.001          0.000         3  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
11                     SPC WE2 · final   전체     SPC 관리도 규칙    사전         0.007          0.049         9  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
12                     SPC WE3 · final   전체     SPC 관리도 규칙    사전         0.027          0.049        16  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
13                     SPC WE4 · final   전체     SPC 관리도 규칙    사전         0.055          0.073        23  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
14                 SPC WE 아무거나 · final   전체     SPC 관리도 규칙    사전         0.076          0.171        43  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
15                      SPC WE1 · std4   전체     SPC 관리도 규칙    사후         0.001          0.000         4  1/25  1/17  0/8      0.250    0.04  0.069    0.193        NaN
16                      SPC WE2 · std4   전체     SPC 관리도 규칙    사후         0.022          0.000        22  1/25  0/17  1/8      0.045    0.04  0.043    0.648        NaN
17                      SPC WE3 · std4   전체     SPC 관리도 규칙    사후         0.106          0.220        59  3/25  0/17  3/8      0.051    0.12  0.071    0.403        NaN
18                      SPC WE4 · std4   전체     SPC 관리도 규칙    사후         0.235          0.293        93  1/25  0/17  1/8      0.011    0.04  0.017    0.980        NaN
19                  SPC WE 아무거나 · std4   전체     SPC 관리도 규칙    사후         0.248          0.390       125  4/25  1/17  3/8      0.032    0.16  0.053    0.701        NaN

                                    방법 대상유형             출처 사후 여부  정상 기준 실제 경보율  불량 없는 Run 경보율  경보(검사) 샷    불량    가스  미성형  Precision  Recall     F1  대상 유형 p  Holm 보정 p
0                              I1 재료부족  미성형           가이드북    사전         0.050          0.049        35  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
1                              I2 쿠션부족  미성형           가이드북    사전         0.037          0.049        66  3/25  3/17  0/8      0.045    0.12  0.066      NaN        NaN
2                             I3 금형 냉각  미성형           가이드북    사전         0.048          0.000         0  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
3                         I4 점도↑(흐름저항)  미성형           가이드북    사전         0.050          0.000        27  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
4                              I5 계량지연   가스           가이드북    사전         0.048          0.024        30  1/25  1/17  0/8      0.033    0.04  0.036    0.626      0.945
5                             I6 체류시간↑   가스           가이드북    사전         0.045          0.000         7  1/25  1/17  0/8      0.143    0.04  0.062    0.163      0.489
6                      I7 공정 흔들림(std4)   가스  RG3 가스에서 온 가설    사후         0.050          0.024        45  2/25  1/17  1/8      0.044    0.08  0.057    0.789        NaN
7                          I8 호퍼 과열 추세   가스  CN7 R1에서 본 신호    사전         0.050          0.293        85  5/25  3/17  2/8      0.059    0.20  0.091    0.473      0.945
8                        미성형 규칙(I1~I4)  미성형        가이드북 묶음    사전         0.045          0.024         8  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
9              미성형 규칙(I1~I4) · 3샷 중 2샷  미성형        가이드북 묶음    사전         0.031          0.000         2  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
10                     가스 규칙(I5·I6·I7)   가스        가이드북 묶음    사후         0.050          0.024        36  3/25  2/17  1/8      0.083    0.12  0.098    0.298        NaN
11           가스 규칙(I5·I6·I7) · 3샷 중 2샷   가스        가이드북 묶음    사후         0.025          0.000        25  1/25  0/17  1/8      0.040    0.04  0.040      NaN        NaN
12            가스 규칙 + 호퍼(I5~I8, 사후 포함)   가스       사후 포함 묶음    사후         0.050          0.244        63  5/25  3/17  2/8      0.079    0.20  0.114    0.271        NaN
13  가스 규칙 + 호퍼(I5~I8, 사후 포함) · 3샷 중 2샷   가스       사후 포함 묶음    사후         0.031          0.244        54  3/25  1/17  2/8      0.056    0.12  0.076    0.827        NaN
14                           전체(I1~I7)   전체        가이드북 묶음    사후         0.050          0.024        26  2/25  2/17  0/8      0.077    0.08  0.078    0.311        NaN
15                 전체(I1~I7) · 3샷 중 2샷   전체        가이드북 묶음    사후         0.026          0.000        15  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
16                     SPC WE1 · final   전체     SPC 관리도 규칙    사전         0.001          0.000         3  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
17                     SPC WE2 · final   전체     SPC 관리도 규칙    사전         0.007          0.049         9  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
18                     SPC WE3 · final   전체     SPC 관리도 규칙    사전         0.027          0.049        16  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
19                     SPC WE4 · final   전체     SPC 관리도 규칙    사전         0.055          0.073        23  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
20                 SPC WE 아무거나 · final   전체     SPC 관리도 규칙    사전         0.076          0.171        43  0/25  0/17  0/8      0.000    0.00  0.000      NaN        NaN
21                      SPC WE1 · std4   전체     SPC 관리도 규칙    사후         0.001          0.000         4  1/25  1/17  0/8      0.250    0.04  0.069    0.193        NaN
22                      SPC WE2 · std4   전체     SPC 관리도 규칙    사후         0.022          0.000        22  1/25  0/17  1/8      0.045    0.04  0.043    0.648        NaN
23                      SPC WE3 · std4   전체     SPC 관리도 규칙    사후         0.106          0.220        59  3/25  0/17  3/8      0.051    0.12  0.071    0.403        NaN
24                      SPC WE4 · std4   전체     SPC 관리도 규칙    사후         0.235          0.293        93  1/25  0/17  1/8      0.011    0.04  0.017    0.980        NaN
25                  SPC WE 아무거나 · std4   전체     SPC 관리도 규칙    사후         0.248          0.390       125  4/25  1/17  3/8      0.032    0.16  0.053    0.701        NaN

## 방향 일치 — 불량 샷에서 지표가 + 쪽인가 (Run 몇 개 중 몇 개)

In [5]:
display(R['direction'].round(3))

     제품               지표 지표가 겨냥한 유형 불량 유형  불량 샷 중앙값  정상 샷 중앙값 + 방향 Run  불량 샷 중 + 비율
0   cn7          I1 재료부족        미성형    가스     0.000     0.000      0/1        0.455
1   cn7          I1 재료부족        미성형   미성형     9.583     0.000      1/2        0.750
2   cn7          I2 쿠션부족        미성형    가스     0.000     0.000      0/1        0.000
3   cn7          I2 쿠션부족        미성형   미성형     2.121     0.000      1/2        0.750
4   cn7         I3 금형 냉각        미성형    가스     0.597    -0.299      1/1        0.636
5   cn7         I3 금형 냉각        미성형   미성형     0.597    -0.299      2/2        1.000
6   cn7     I4 점도↑(흐름저항)        미성형    가스     0.000     0.000      0/1        0.455
7   cn7     I4 점도↑(흐름저항)        미성형   미성형   -20.000     0.000      1/2        0.250
8   cn7          I5 계량지연         가스    가스     0.250     0.000      1/1        0.545
9   cn7          I5 계량지연         가스   미성형     0.125     0.000      1/2        0.500
10  cn7         I6 체류시간↑         가스    가스     0.000     0.000      0/1        0.182
11  cn7         I6 체류시간↑         가스   미성형    -0.990     0.000      0/2        0.250
12  cn7  I7 공정 흔들림(std4)         가스    가스     0.661     0.133      1/1        0.727
13  cn7  I7 공정 흔들림(std4)         가스   미성형    -0.101     0.133      1/2        0.500
14  cn7      I8 호퍼 과열 추세         가스    가스     0.633     0.035      1/1        0.818
15  cn7      I8 호퍼 과열 추세         가스   미성형     0.834     0.035      1/2        0.750
16  rg3          I1 재료부족        미성형    가스     0.000     0.000      1/4        0.412
17  rg3          I1 재료부족        미성형   미성형     0.096     0.000      1/4        0.500
18  rg3          I2 쿠션부족        미성형    가스     0.000     0.000      1/4        0.235
19  rg3          I2 쿠션부족        미성형   미성형     0.000     0.000      0/4        0.250
20  rg3         I3 금형 냉각        미성형    가스    -0.337     0.000      0/4        0.176
21  rg3         I3 금형 냉각        미성형   미성형    -0.125     0.000      1/4        0.250
22  rg3     I4 점도↑(흐름저항)        미성형    가스    -0.167     0.000      1/4        0.294
23  rg3     I4 점도↑(흐름저항)        미성형   미성형    -0.083     0.000      2/4        0.375
24  rg3          I5 계량지연         가스    가스     0.000     0.000      2/4        0.471
25  rg3          I5 계량지연         가스   미성형     0.717     0.000      3/4        0.750
26  rg3         I6 체류시간↑         가스    가스     0.000     0.000      0/4        0.176
27  rg3         I6 체류시간↑         가스   미성형     0.000     0.000      0/4        0.000
28  rg3  I7 공정 흔들림(std4)         가스    가스     0.052     0.000      3/4        0.529
29  rg3  I7 공정 흔들림(std4)         가스   미성형     0.426     0.000      3/4        0.625
30  rg3      I8 호퍼 과열 추세         가스    가스    -0.293     0.115      1/4        0.471
31  rg3      I8 호퍼 과열 추세         가스   미성형     0.618     0.115      3/4        0.750

## 읽는 법
1. **Holm 보정 p < 0.05 인 '사전' 규칙**만 '도메인 지식이 데이터로 확인됨'이라고 쓸 수 있음
2. `정상 기준 실제 경보율` vs `불량 없는 Run 경보율`: 비슷해야 현장 기준으로 그대로 쓸 수 있음
3. SPC 규칙은 경보율을 맞추지 않은 고정 규칙 → 정상 기준 경보율이 너무 높으면(>5%) 현장 사용 어려움
4. 방향 표에서 '+ 방향 Run'이 1/1이면 에피소드 1개 → 사례 수준. RG3처럼 Run 여러 개에서 일관되면 근거가 강함
5. 규칙이 못 잡아도 의미 있음: '가이드북의 대표 원인 지표로는 이 데이터의 가스가 설명되지 않는다' = 보고서의 한계·향후 센서 제안 근거