# 50. 공정 흐름 감시 신호 — 46·47·48번 단서로 만든 신호 + 정직한 검증

| 신호 (라벨 미사용) | 내용 | 나온 곳 |
|---|---|---|
| S1 EWMA·std4 | 흔들림 점수의 지수 이동평균 | 46번 RG3 미성형 (사후 선택) |
| S2 과열 드리프트 | 배럴2~5·호퍼 최근 30샷 평균 − 재가동 11~30샷 기준선 (**고정 기준선**) | 47번: 실제 가스 = 약한 과열(0.2~0.5배) → 누적 필요 |
| S3 계량 수준 이동 | 계량시간·사이클 최근 10샷 평균 − 고정 기준선 | 47·48번: RG3 미성형 = 계량지연형 |
| S4 변수 관계 변화 | 배럴·호퍼·계량시간 15쌍의 20샷 이동 상관이 정상과 다른 정도 | 새 가설 (히터 제어·공급 불안정) |
| S5 / S6 | 미성형 후보(S1 or S3) / 가스 후보(S2 or S4) | 결합 |

**46번에서 고친 점**: 재가동 후 10샷은 경보 제외(Run 시작 착시 제거), 누적형 대신 창(window) 방식(기준 보정 문제 회피)

**검증**
- `p_` = 원형 이동 순열 / **`보정p_` = 신호 6개 × 경보율 3개 중 최고를 고른 효과까지 뺀 p** ← 이게 0.05 아래여야 '신뢰'
- `[같은 K]` = 같은 검사 샷 수로 단발 std4 / 최종 모델 점수를 썼을 때
- 47번 주입 실험 재사용: 새 신호가 서서히 변하는 이상·계량지연을 잡는지
- 실행 시간: 본 실행 수 분 + 주입 확인 제품당 수 분 + (선택) RG3 결합 순열 수십 분

In [1]:
import pandas as pd
pd.set_option('display.width', 250); pd.set_option('display.max_columns', 40); pd.set_option('display.max_rows', 300)
%load_ext autoreload
%autoreload 2
import flow_monitor as FM
R = FM.run(products=('cn7', 'rg3'), n_perm=1000, n_adj=2000)

[cn7] 완료
[rg3] 완료

## CN7 — 경보율 5% / 10%

In [2]:
display(FM.view(R, 'cn7', 0.05).round(3))
display(FM.view(R, 'cn7', 0.10).round(3))

,방법,출처,경보(검사) 샷,불량 없는 Run 경보율,불량,가스,미성형,Precision,F1,p_가스,보정p_가스,p_미성형,보정p_미성형,[같은 K] 단발 std4 상위 K 불량,[같은 K] 단발 std4 상위 K 가스,[같은 K] 단발 std4 상위 K 미성형,[같은 K] 최종 모델 점수 상위 K 불량,[같은 K] 최종 모델 점수 상위 K 가스,[같은 K] 최종 모델 점수 상위 K 미성형
0,S1 EWMA·std4,46번 RG3 미성형에서 고름(사후),159,0.040,4/15,4/11,0/4,0.025,0.046,0.288,0.387,NaN,NaN,3/15,3/11,0/4,5/15,2/11,3/4
1,S2 과열 드리프트,47번 실제 가스 방향,0,0.000,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,0/15,0/11,0/4,1/15,0/11,1/4
2,S3 계량 수준 이동,47·48번 RG3 미성형 방향,2,0.002,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,0/15,0/11,0/4,2/15,0/11,2/4
3,S4 변수 관계 변화,새 가설(사전),186,0.107,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,5/15,5/11,0/4,5/15,2/11,3/4
4,S5 미성형 후보(S1|S3),결합,93,0.023,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,1/15,1/11,0/4,4/15,1/11,3/4
5,S6 가스 후보(S2|S4),결합,129,0.077,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,1/15,1/11,0/4,4/15,1/11,3/4

,방법,출처,경보(검사) 샷,불량 없는 Run 경보율,불량,가스,미성형,Precision,F1,p_가스,보정p_가스,p_미성형,보정p_미성형,[같은 K] 단발 std4 상위 K 불량,[같은 K] 단발 std4 상위 K 가스,[같은 K] 단발 std4 상위 K 미성형,[같은 K] 최종 모델 점수 상위 K 불량,[같은 K] 최종 모델 점수 상위 K 가스,[같은 K] 최종 모델 점수 상위 K 미성형
0,S1 EWMA·std4,46번 RG3 미성형에서 고름(사후),250,0.083,6/15,6/11,0/4,0.024,0.045,0.249,0.287,NaN,NaN,5/15,5/11,0/4,5/15,2/11,3/4
1,S2 과열 드리프트,47번 실제 가스 방향,0,0.000,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,0/15,0/11,0/4,1/15,0/11,1/4
2,S3 계량 수준 이동,47·48번 RG3 미성형 방향,2,0.002,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,0/15,0/11,0/4,2/15,0/11,2/4
3,S4 변수 관계 변화,새 가설(사전),299,0.161,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,5/15,5/11,0/4,5/15,2/11,3/4
4,S5 미성형 후보(S1|S3),결합,161,0.042,4/15,4/11,0/4,0.025,0.045,0.288,0.387,NaN,NaN,3/15,3/11,0/4,5/15,2/11,3/4
5,S6 가스 후보(S2|S4),결합,190,0.110,0/15,0/11,0/4,0.000,0.000,NaN,NaN,NaN,NaN,5/15,5/11,0/4,5/15,2/11,3/4

## RG3 — 경보율 5% / 10%

In [3]:
display(FM.view(R, 'rg3', 0.05).round(3))
display(FM.view(R, 'rg3', 0.10).round(3))

,방법,출처,경보(검사) 샷,불량 없는 Run 경보율,불량,가스,미성형,Precision,F1,p_가스,보정p_가스,p_미성형,보정p_미성형,[같은 K] 단발 std4 상위 K 불량,[같은 K] 단발 std4 상위 K 가스,[같은 K] 단발 std4 상위 K 미성형,[같은 K] 최종 모델 점수 상위 K 불량,[같은 K] 최종 모델 점수 상위 K 가스,[같은 K] 최종 모델 점수 상위 K 미성형
0,S1 EWMA·std4,46번 RG3 미성형에서 고름(사후),15,0.000,2/25,0/17,2/8,0.133,0.100,NaN,NaN,0.016,0.332,2/25,1/17,1/8,0/25,0/17,0/8
1,S2 과열 드리프트,47번 실제 가스 방향,0,0.000,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,0/25,0/17,0/8,0/25,0/17,0/8
2,S3 계량 수준 이동,47·48번 RG3 미성형 방향,4,0.000,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,1/25,1/17,0/8,0/25,0/17,0/8
3,S4 변수 관계 변화,새 가설(사전),54,0.317,2/25,2/17,0/8,0.037,0.051,0.371,0.768,NaN,NaN,2/25,1/17,1/8,1/25,1/17,0/8
4,S5 미성형 후보(S1|S3),결합,9,0.000,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,1/25,1/17,0/8,0/25,0/17,0/8
5,S6 가스 후보(S2|S4),결합,32,0.244,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,2/25,1/17,1/8,1/25,1/17,0/8

,방법,출처,경보(검사) 샷,불량 없는 Run 경보율,불량,가스,미성형,Precision,F1,p_가스,보정p_가스,p_미성형,보정p_미성형,[같은 K] 단발 std4 상위 K 불량,[같은 K] 단발 std4 상위 K 가스,[같은 K] 단발 std4 상위 K 미성형,[같은 K] 최종 모델 점수 상위 K 불량,[같은 K] 최종 모델 점수 상위 K 가스,[같은 K] 최종 모델 점수 상위 K 미성형
0,S1 EWMA·std4,46번 RG3 미성형에서 고름(사후),36,0.000,4/25,1/17,3/8,0.111,0.131,0.683,0.977,0.016,0.072,2/25,1/17,1/8,1/25,1/17,0/8
1,S2 과열 드리프트,47번 실제 가스 방향,0,0.000,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,0/25,0/17,0/8,0/25,0/17,0/8
2,S3 계량 수준 이동,47·48번 RG3 미성형 방향,7,0.000,0/25,0/17,0/8,0.000,0.000,NaN,NaN,NaN,NaN,1/25,1/17,0/8,0/25,0/17,0/8
3,S4 변수 관계 변화,새 가설(사전),83,0.415,3/25,2/17,1/8,0.036,0.056,0.690,0.768,0.629,0.831,3/25,1/17,2/8,2/25,1/17,1/8
4,S5 미성형 후보(S1|S3),결합,22,0.000,2/25,0/17,2/8,0.091,0.085,NaN,NaN,0.026,0.332,2/25,1/17,1/8,1/25,1/17,0/8
5,S6 가스 후보(S2|S4),결합,55,0.341,2/25,2/17,0/8,0.036,0.050,0.371,0.768,NaN,NaN,2/25,1/17,1/8,1/25,1/17,0/8

## 에피소드 (재가동 10샷 제외 후) — 미성형 전에 경보가 났나, 그 Run 가스를 몇 개 잡았나 (경보율 5%)

In [4]:
display(R['episodes'].round(2))

     제품     Run                방법   경보율  Run 불량  Run 가스  첫 불량 seq  첫 미성형 seq  첫 경보 seq  Run 안 경보 수  잡은 가스  잡은 미성형  미성형 직전 50샷 경보
0   cn7  cn7_R1      S1 EWMA·std4  0.05      14      11        25         59      52.0          50      4       0              4
1   cn7  cn7_R1        S2 과열 드리프트  0.05      14      11        25         59       NaN           0      0       0              0
2   cn7  cn7_R1       S3 계량 수준 이동  0.05      14      11        25         59       NaN           0      0       0              0
3   cn7  cn7_R1       S4 변수 관계 변화  0.05      14      11        25         59      11.0           1      0       0              1
4   cn7  cn7_R1  S5 미성형 후보(S1|S3)  0.05      14      11        25         59     109.0          37      0       0              0
5   cn7  cn7_R1   S6 가스 후보(S2|S4)  0.05      14      11        25         59      11.0           1      0       0              1
6   cn7  cn7_R6      S1 EWMA·std4  0.05       1       0       248        248     144.0          56      0       0              0
7   cn7  cn7_R6        S2 과열 드리프트  0.05       1       0       248        248       NaN           0      0       0              0
8   cn7  cn7_R6       S3 계량 수준 이동  0.05       1       0       248        248       NaN           0      0       0              0
9   cn7  cn7_R6       S4 변수 관계 변화  0.05       1       0       248        248      11.0          44      0       0              0
10  cn7  cn7_R6  S5 미성형 후보(S1|S3)  0.05       1       0       248        248     263.0          26      0       0              0
11  cn7  cn7_R6   S6 가스 후보(S2|S4)  0.05       1       0       248        248      11.0          26      0       0              0
12  rg3  rg3_R2      S1 EWMA·std4  0.05       5       4        28         45      11.0           3      0       0              3
13  rg3  rg3_R2        S2 과열 드리프트  0.05       5       4        28         45       NaN           0      0       0              0
14  rg3  rg3_R2       S3 계량 수준 이동  0.05       5       4        28         45       NaN           0      0       0              0
15  rg3  rg3_R2       S4 변수 관계 변화  0.05       5       4        28         45      11.0           4      1       0              1
16  rg3  rg3_R2  S5 미성형 후보(S1|S3)  0.05       5       4        28         45      11.0           3      0       0              3
17  rg3  rg3_R2   S6 가스 후보(S2|S4)  0.05       5       4        28         45      11.0           1      0       0              1
18  rg3  rg3_R3      S1 EWMA·std4  0.05      10       6         7          9      45.0           4      0       0              0
19  rg3  rg3_R3        S2 과열 드리프트  0.05      10       6         7          9       NaN           0      0       0              0
20  rg3  rg3_R3       S3 계량 수준 이동  0.05      10       6         7          9       NaN           0      0       0              0
21  rg3  rg3_R3       S4 변수 관계 변화  0.05      10       6         7          9      69.0          17      0       0              0
22  rg3  rg3_R3  S5 미성형 후보(S1|S3)  0.05      10       6         7          9       NaN           0      0       0              0
23  rg3  rg3_R3   S6 가스 후보(S2|S4)  0.05      10       6         7          9     135.0           5      0       0              0
24  rg3  rg3_R4      S1 EWMA·std4  0.05       4       3         3         65       NaN           0      0       0              0
25  rg3  rg3_R4        S2 과열 드리프트  0.05       4       3         3         65       NaN           0      0       0              0
26  rg3  rg3_R4       S3 계량 수준 이동  0.05       4       3         3         65       NaN           0      0       0              0
27  rg3  rg3_R4       S4 변수 관계 변화  0.05       4       3         3         65      11.0          13      1       0              9
28  rg3  rg3_R4  S5 미성형 후보(S1|S3)  0.05       4       3         3         65       NaN           0      0       0              0
29  rg3  rg3_R4   S6 가스 후보(S2|S4)  0.05       4       3         3         65      11.0          10      0       0              6
30  rg3  rg3_R5      S1 EWMA·std4  0.05       6       4        33         62      62.0           8      0       2              0
31  rg3  rg3_R5        S2 과열 드리프트  0.05       6       4        33         62       NaN           0      0       0              0
32  rg3  rg3_R5       S3 계량 수준 이동  0.05       6       4        33         62      84.0           4      0       0              0
33  rg3  rg3_R5       S4 변수 관계 변화  0.05       6       4        33         62      11.0           7      0       0              2
34  rg3  rg3_R5  S5 미성형 후보(S1|S3)  0.05       6       4        33         62      63.0           6      0       0              0
35  rg3  rg3_R5   S6 가스 후보(S2|S4)  0.05       6       4        33         62      11.0           6      0       0              2

## 운전 단계 — 재가동 후 몇 샷째에 불량이 몰렸나 (R1 가스가 예열 단계인지)

In [5]:
display(R['phase'].round(3))

     제품       구간  평가 샷  가스  미성형  가스 비율  미성형 비율
0   cn7     1~10   113   0    0  0.000   0.000
1   cn7    11~30   208   1    0  0.005   0.000
2   cn7    31~60   274  10    2  0.036   0.007
3   cn7   61~100   293   0    1  0.000   0.003
4   cn7  101~300   805   0    1  0.000   0.001
5   cn7     301~   281   0    0  0.000   0.000
6   rg3     1~10    70   2    1  0.029   0.014
7   rg3    11~30   138   7    0  0.051   0.000
8   rg3    31~60   126   2    3  0.016   0.024
9   rg3   61~100    84   3    3  0.036   0.036
10  rg3  101~300   173   3    1  0.017   0.006
11  rg3     301~     0   0    0    NaN     NaN

## RG3 미성형 EWMA·std4 — 46번 전체 탐색(방법 17 × 경보율 4) 기준으로 보정한 p
`보정p_미성형`이 0.05보다 크면 46번에서 본 3/8·5/8은 '많이 찾아보면 나올 수 있는 수준'

In [6]:
A46 = FM.adjusted_46('rg3', n=2000)
display(A46.head(10).round(3))

  [rg3] final 완료
  [rg3] std4 완료
  [rg3] thermal 완료

                       방법|경보율  경보 샷  미성형  보정p_불량  보정p_가스  보정p_미성형
0            BOCPD · std4|0.1   123  5/8   0.140   0.887    0.013
1      EWMA(λ=0.2) · std4|0.1    43  3/8   0.901   1.000    0.319
2           BOCPD · std4|0.05    88  3/8   0.508   0.887    0.319
3               단발 · std4|0.1    66  2/8   0.984   1.000    0.732
4            단발 · thermal|0.1    68  2/8   0.901   0.989    0.732
5  MEWMA(λ=0.3) · 최종 17변수|0.1    62  2/8   1.000     NaN    0.732
6     EWMA(λ=0.2) · std4|0.05    21  2/8   1.000     NaN    0.732
7              단발 · final|0.1    62  1/8   1.000   1.000    0.973
8              단발 · std4|0.05    45  1/8   1.000   1.000    0.973
9           BOCPD · final|0.1    72  1/8   1.000   1.000    0.973

## 47번 주입 실험으로 새 신호 확인 (정상 기준 경보율 1%) — 최종 모델이 못 잡던 패턴을 잡나

In [7]:
SC = FM.synthetic_check(('cn7', 'rg3'), n_ep=150, R=R)
for p in ('cn7', 'rg3')
    print(f'===== {p} 에피소드 탐지율')
    display(FM.synthetic_pivot(SC, p))
    print(f'===== {p} 뒤 5샷 탐지율 (지속 이상을 끝까지 잡나)')
    display(FM.synthetic_pivot(SC, p, '뒤 5샷 탐지율'))

  [cn7] 주입 확인 완료
  [rg3] 주입 확인 완료
===== cn7 에피소드 탐지율

탐지기           최종 모델 q0.999  std4 q0.999  S1 EWMA·std4  S2 과열 드리프트  S3 계량 수준 이동  S4 변수 관계 변화  S5 미성형 후보(S1|S3)  S6 가스 후보(S2|S4)
패턴       크기
주입 없음    0.0          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
미성형_재료부족 0.5          0.01         0.01          0.07        0.00         0.00         0.06              0.05             0.03
         1.0          0.01         0.04          0.92        0.00         0.00         0.06              0.81             0.03
         2.0          0.01         1.00          1.00        0.00         0.00         0.06              1.00             0.03
         3.0          0.05         1.00          1.00        0.00         0.00         0.06              1.00             0.03
         5.0          1.00         1.00          1.00        0.00         0.00         0.06              1.00             0.03
         8.0          1.00         1.00          1.00        0.00         0.00         0.06              1.00             0.03
미성형_냉각점도 0.5          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
         1.0          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
         2.0          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
         3.0          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
         5.0          0.01         0.01          0.02        0.00         0.00         0.06              0.02             0.03
         8.0          0.13         0.01          0.02        0.00         0.00         0.06              0.02             0.03
가스_과열    0.5          0.01         0.01          0.02        0.00         0.00         0.10              0.02             0.07
         1.0          0.01         0.01          0.05        0.00         0.01         0.30              0.03             0.21
         2.0          0.01         0.01          0.33        0.00         0.01         0.95              0.17             0.93
         3.0          0.01         0.17          1.00        0.41         0.03         1.00              0.99             1.00
         5.0          0.01         1.00          1.00        1.00         0.38         1.00              1.00             1.00
         8.0          1.00         1.00          1.00        1.00         1.00         1.00              1.00             1.00
가스_공급불안정 0.5          0.01         0.72          1.00        0.00         0.00         0.21              0.99             0.11
         1.0          0.01         1.00          1.00        0.00         0.00         0.50              1.00             0.34
         2.0          0.53         1.00          1.00        0.00         0.00         0.84              1.00             0.70
         3.0          0.97         1.00          1.00        0.00         0.02         0.97              1.00             0.95
         5.0          1.00         1.00          1.00        0.00         0.08         1.00              1.00             1.00
         8.0          1.00         1.00          1.00        0.01         0.27         1.00              1.00             1.00
가스_계량지연  0.5          0.01         0.01          0.02        0.00         0.01         0.07              0.03             0.05
         1.0          0.01         0.01          0.02        0.00         0.04         0.23              0.03             0.13
         2.0          0.01         0.01          0.02        0.00         0.59         0.35              0.35             0.26
         3.0          0.01         0.01          0.02        0.00         1.00         0.41              1.00             0.32
         5.0          0.02         0.01          0.02        0.00         1.00         0.47              1.00             0.35
         8.0          0.17         0.01          0.02        0.00         1.00         0.51              1.00             0.39

===== cn7 뒤 5샷 탐지율 (지속 이상을 끝까지 잡나)

탐지기           최종 모델 q0.999  std4 q0.999  S1 EWMA·std4  S2 과열 드리프트  S3 계량 수준 이동  S4 변수 관계 변화  S5 미성형 후보(S1|S3)  S6 가스 후보(S2|S4)
패턴       크기
주입 없음    0.0          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
미성형_재료부족 0.5          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         1.0          0.00         0.00          0.01        0.00         0.00         0.01              0.00             0.00
         2.0          0.00         0.00          0.01        0.00         0.00         0.01              0.00             0.00
         3.0          0.00         0.00          0.01        0.00         0.00         0.01              0.00             0.00
         5.0          0.00         0.00          0.01        0.00         0.00         0.01              0.00             0.00
         8.0          0.00         0.00          0.01        0.00         0.00         0.01              0.00             0.00
미성형_냉각점도 0.5          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         1.0          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         2.0          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         3.0          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         5.0          0.00         0.00          0.00        0.00         0.00         0.01              0.00             0.00
         8.0          0.04         0.00          0.00        0.00         0.00         0.01              0.00             0.00
가스_과열    0.5          0.00         0.00          0.00        0.00         0.00         0.02              0.00             0.01
         1.0          0.00         0.00          0.01        0.00         0.00         0.12              0.00             0.07
         2.0          0.00         0.00          0.14        0.00         0.01         0.81              0.06             0.73
         3.0          0.00         0.02          0.88        0.12         0.02         0.99              0.78             0.99
         5.0          0.00         0.83          1.00        0.93         0.19         1.00              1.00             1.00
         8.0          1.00         1.00          1.00        1.00         0.94         1.00              1.00             1.00
가스_공급불안정 0.5          0.00         0.38          0.99        0.00         0.00         0.06              0.99             0.03
         1.0          0.00         1.00          1.00        0.00         0.00         0.11              1.00             0.06
         2.0          0.01         1.00          1.00        0.00         0.00         0.16              1.00             0.12
         3.0          0.09         1.00          1.00        0.00         0.00         0.17              1.00             0.12
         5.0          0.30         1.00          1.00        0.00         0.02         0.19              1.00             0.13
         8.0          0.38         1.00          1.00        0.00         0.08         0.20              1.00             0.14
가스_계량지연  0.5          0.00         0.00          0.00        0.00         0.01         0.01              0.00             0.01
         1.0          0.00         0.00          0.00        0.00         0.01         0.03              0.01             0.01
         2.0          0.00         0.00          0.00        0.00         0.40         0.07              0.19             0.04
         3.0          0.00         0.00          0.00        0.00         1.00         0.10              1.00             0.05
         5.0          0.00         0.00          0.00        0.00         1.00         0.13              1.00             0.08
         8.0          0.00         0.00          0.00        0.00         1.00         0.14              1.00             0.09

===== rg3 에피소드 탐지율

탐지기           최종 모델 q0.999  std4 q0.999  S1 EWMA·std4  S2 과열 드리프트  S3 계량 수준 이동  S4 변수 관계 변화  S5 미성형 후보(S1|S3)  S6 가스 후보(S2|S4)
패턴       크기
주입 없음    0.0          0.00         0.01          0.03        0.00         0.06         0.07              0.07             0.03
미성형_재료부족 0.5          0.00         0.01          0.04        0.00         0.06         0.07              0.07             0.03
         1.0          0.00         0.01          0.05        0.00         0.06         0.07              0.08             0.03
         2.0          0.00         0.02          0.06        0.00         0.06         0.07              0.09             0.03
         3.0          0.22         0.03          0.09        0.00         0.06         0.07              0.11             0.03
         5.0          0.95         0.58          0.67        0.00         0.06         0.07              0.61             0.03
         8.0          1.00         1.00          1.00        0.00         0.06         0.07              1.00             0.03
미성형_냉각점도 0.5          0.00         0.01          0.03        0.00         0.06         0.07              0.07             0.03
         1.0          0.00         0.01          0.03        0.00         0.06         0.07              0.07             0.03
         2.0          0.00         0.01          0.03        0.00         0.06         0.07              0.07             0.03
         3.0          0.01         0.01          0.03        0.00         0.06         0.07              0.07             0.03
         5.0          0.01         0.01          0.03        0.00         0.06         0.07              0.07             0.03
         8.0          0.11         0.01          0.03        0.00         0.06         0.07              0.07             0.03
가스_과열    0.5          0.00         0.01          0.03        0.00         0.08         0.11              0.07             0.07
         1.0          0.00         0.01          0.03        0.00         0.10         0.29              0.08             0.22
         2.0          0.00         0.01          0.03        0.21         0.16         0.68              0.11             0.65
         3.0          0.00         0.01          0.03        0.94         0.21         0.99              0.15             0.99
         5.0          0.00         0.03          0.06        1.00         0.75         1.00              0.42             1.00
         8.0          0.00         0.44          0.86        1.00         0.99         1.00              0.99             1.00
가스_공급불안정 0.5          0.00         0.01          0.06        0.00         0.06         0.10              0.09             0.08
         1.0          0.00         0.14          0.29        0.00         0.08         0.22              0.27             0.17
         2.0          0.00         0.99          1.00        0.00         0.11         0.44              1.00             0.35
         3.0          0.05         1.00          1.00        0.00         0.13         0.62              1.00             0.53
         5.0          0.45         1.00          1.00        0.01         0.23         0.87              1.00             0.84
         8.0          0.89         1.00          1.00        0.06         0.43         0.99              1.00             0.98
가스_계량지연  0.5          0.00         0.01          0.03        0.00         0.16         0.09              0.11             0.05
         1.0          0.00         0.01          0.03        0.00         0.23         0.09              0.20             0.05
         2.0          0.00         0.01          0.03        0.00         0.94         0.11              0.65             0.07
         3.0          0.00         0.01          0.03        0.00         0.99         0.15              0.99             0.07
         5.0          0.00         0.01          0.03        0.00         1.00         0.19              1.00             0.11
         8.0          0.20         0.01          0.03        0.00         1.00         0.23              1.00             0.13

===== rg3 뒤 5샷 탐지율 (지속 이상을 끝까지 잡나)

탐지기           최종 모델 q0.999  std4 q0.999  S1 EWMA·std4  S2 과열 드리프트  S3 계량 수준 이동  S4 변수 관계 변화  S5 미성형 후보(S1|S3)  S6 가스 후보(S2|S4)
패턴       크기
주입 없음    0.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
미성형_재료부족 0.5          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         1.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         2.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         3.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         5.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         8.0          0.00         0.00          0.02        0.00         0.02         0.01              0.02             0.00
미성형_냉각점도 0.5          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         1.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         2.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         3.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         5.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
         8.0          0.00         0.00          0.01        0.00         0.02         0.01              0.02             0.00
가스_과열    0.5          0.00         0.00          0.01        0.00         0.03         0.03              0.02             0.02
         1.0          0.00         0.00          0.01        0.00         0.03         0.14              0.03             0.11
         2.0          0.00         0.00          0.01        0.08         0.06         0.48              0.04             0.48
         3.0          0.00         0.00          0.01        0.55         0.08         0.90              0.06             0.92
         5.0          0.00         0.01          0.01        0.99         0.41         1.00              0.18             1.00
         8.0          0.00         0.10          0.65        1.00         0.96         1.00              0.95             1.00
가스_공급불안정 0.5          0.00         0.00          0.02        0.00         0.02         0.02              0.03             0.01
         1.0          0.00         0.05          0.17        0.00         0.03         0.02              0.14             0.01
         2.0          0.00         0.77          1.00        0.00         0.03         0.04              0.99             0.03
         3.0          0.00         1.00          1.00        0.00         0.03         0.05              1.00             0.03
         5.0          0.01         1.00          1.00        0.00         0.06         0.05              1.00             0.04
         8.0          0.10         1.00          1.00        0.04         0.15         0.06              1.00             0.06
가스_계량지연  0.5          0.00         0.00          0.01        0.00         0.04         0.02              0.03             0.01
         1.0          0.00         0.00          0.01        0.00         0.08         0.02              0.06             0.01
         2.0          0.00         0.00          0.01        0.00         0.74         0.02              0.39             0.01
         3.0          0.00         0.00          0.01        0.00         0.99         0.02              0.97             0.01
         5.0          0.00         0.00          0.01        0.00         1.00         0.03              1.00             0.01
         8.0          0.00         0.00          0.01        0.00         1.00         0.04              1.00             0.02

## RG3: 가스 RF + 라벨 없는 미성형 후보 결합 vs N1 (시드 3개 평균)

In [8]:
RC = FM.rg3_combo(R)
display(RC['summary'].round(3))

                                   모델 검사 비율  검사_샷      불량     가스    미성형 미성형_범위  Precision  Recall     F1
0       가스 RF + S1 EWMA·std4 (g=0.68)    5%    30   2.000  1.000  1.000    1~1      0.067   0.080  0.073
1       가스 RF + S1 EWMA·std4 (g=0.68)   10%    60   9.000  5.333  3.667    3~4      0.150   0.360  0.212
2       가스 RF + S1 EWMA·std4 (g=0.68)   15%    89  12.000  7.667  4.333    4~5      0.135   0.480  0.211
3        가스 RF + S1 EWMA·std4 (g=0.5)    5%    30   3.667  1.000  2.667    2~3      0.122   0.147  0.133
4        가스 RF + S1 EWMA·std4 (g=0.5)   10%    60   8.667  4.333  4.333    4~5      0.144   0.347  0.204
5        가스 RF + S1 EWMA·std4 (g=0.5)   15%    89  10.667  6.000  4.667    4~5      0.120   0.427  0.187
6        가스 RF + S3 계량 수준 이동 (g=0.68)    5%    30   3.000  1.000  2.000    2~2      0.100   0.120  0.109
7        가스 RF + S3 계량 수준 이동 (g=0.68)   10%    60   8.000  5.333  2.667    2~3      0.133   0.320  0.188
8        가스 RF + S3 계량 수준 이동 (g=0.68)   15%    89  10.333  7.667  2.667    2~3      0.116   0.413  0.181
9         가스 RF + S3 계량 수준 이동 (g=0.5)    5%    30   2.667  1.000  1.667    1~2      0.089   0.107  0.097
10        가스 RF + S3 계량 수준 이동 (g=0.5)   10%    60   6.667  4.333  2.333    2~3      0.111   0.267  0.157
11        가스 RF + S3 계량 수준 이동 (g=0.5)   15%    89   8.667  6.000  2.667    2~3      0.097   0.347  0.152
12  가스 RF + S5 미성형 후보(S1|S3) (g=0.68)    5%    30   2.000  1.000  1.000    1~1      0.067   0.080  0.073
13  가스 RF + S5 미성형 후보(S1|S3) (g=0.68)   10%    60   9.000  5.333  3.667    3~4      0.150   0.360  0.212
14  가스 RF + S5 미성형 후보(S1|S3) (g=0.68)   15%    89  11.333  7.667  3.667    3~4      0.127   0.453  0.199
15   가스 RF + S5 미성형 후보(S1|S3) (g=0.5)    5%    30   1.667  1.000  0.667    0~1      0.056   0.067  0.061
16   가스 RF + S5 미성형 후보(S1|S3) (g=0.5)   10%    60   7.667  4.333  3.333    3~4      0.128   0.307  0.180
17   가스 RF + S5 미성형 후보(S1|S3) (g=0.5)   15%    89  10.667  6.000  4.667    4~5      0.120   0.427  0.187
18                             가스 RF만    5%    30   5.667  4.333  1.333    1~2      0.189   0.227  0.206
19                             가스 RF만   10%    60   9.333  7.667  1.667    1~2      0.156   0.373  0.220
20                             가스 RF만   15%    89  10.000  8.000  2.000    2~2      0.112   0.400  0.175
21   가스 RF + N1 (41·43번, 비교) (g=0.68)    5%    30   3.333  1.000  2.333    2~3      0.111   0.133  0.121
22   가스 RF + N1 (41·43번, 비교) (g=0.68)   10%    60   9.000  6.000  3.000    3~3      0.150   0.360  0.212
23   가스 RF + N1 (41·43번, 비교) (g=0.68)   15%    89  11.333  7.667  3.667    3~4      0.127   0.453  0.199
24    가스 RF + N1 (41·43번, 비교) (g=0.5)    5%    30   3.000  1.000  2.000    1~3      0.100   0.120  0.109
25    가스 RF + N1 (41·43번, 비교) (g=0.5)   10%    60   9.333  6.000  3.333    3~4      0.156   0.373  0.220
26    가스 RF + N1 (41·43번, 비교) (g=0.5)   15%    89  12.000  8.333  3.667    3~4      0.135   0.480  0.211

### (선택) 결합 순열 검증 — 가스 RF만 재학습, 30번에 수십 분

In [9]:
# display(FM.rg3_combo_permutation(RC, short='S1 EWMA·std4', share=0.68, rate=0.10, n=30))

## 읽는 법
1. **보정p < 0.05** 인 신호만 '흐름으로 탐지된다'고 주장 가능. p_만 낮고 보정p가 높으면 '찾아보면 나오는 수준'
2. `불량 없는 Run 경보율`이 목표 경보율과 비슷해야 현장 기준으로 그대로 쓸 수 있음 (46번 CUSUM 문제 재발 여부)
3. 주입 실험: S2가 가스_과열·미성형_냉각점도를, S3가 가스_계량지연을 **뒤 5샷까지** 잡으면 → 고정 기준선이 47번 한계(적응)를 해결
4. 주입에서는 잡는데 실제 불량에서 못 잡으면 → '실제 불량은 그 패턴/크기가 아니다' (데이터 한계로 보고)
5. RG3 결합: N1(라벨 사용)과 비슷하면 **라벨 없이도 같은 성능** → 현장 적용성 측면 장점 (단, 순열 p 확인)